# Design Hierarchy  
Each item here is coded as: __Instance__ (Module from file)  

* __PipeIntMul__ (PipeIntMul.v)
  * __control__ (PipeIntMul_ctrl from PipeIntMul_ctrl.v)
  * __datapath__ (PipeIntMul_datapath from PipeIntMul_datapath.v)
    * __C0_MUL__ (IterIntMul from IterIntMul.v)
      * __IMULDP__ (IterIntMul_datapath from IterIntMul_datapath.v)
      * __IMULCT__ (IterIntMul_ctrl from IterIntMul_ctrl.v)
    * __C1_MUL__ (IterIntMul from IterIntMul.v)
      * __IMULDP__ (IterIntMul_datapath from IterIntMul_datapath.v)
      * __IMULCT__ (IterIntMul_ctrl from IterIntMul_ctrl.v)
    * __C2_MUL__ (IterIntMul from IterIntMul.v)
      * __IMULDP__ (IterIntMul_datapath from IterIntMul_datapath.v)
      * __IMULCT__ (IterIntMul_ctrl from IterIntMul_ctrl.v)
    * __C3_MUL__ (IterIntMul from IterIntMul.v)
      * __IMULDP__ (IterIntMul_datapath from IterIntMul_datapath.v)
      * __IMULCT__ (IterIntMul_ctrl from IterIntMul_ctrl.v)
    * __A3_MF_REG__ (PipelineReg8 from PipelineReg.v)
    * __A2_MF_REG__ (PipelineReg8 from PipelineReg.v)
    * __A1_MF_REG__ (PipelineReg8 from PipelineReg.v)
    * __A0_MF_REG__ (PipelineReg8 from PipelineReg.v)
    * __B_MF_REG__ (PipelineReg32 from PipelineReg.v)
    * __A3_C0_REG__ (PipelineReg8 from PipelineReg.v)
    * __A2_C0_REG__ (PipelineReg8 from PipelineReg.v)
    * __A1_C0_REG__ (PipelineReg8 from PipelineReg.v)
    * __P0_C0_REG__ (PipelineReg40 from PipelineReg.v)
    * __B_C0_REG__ (PipelineReg32 from PipelineReg.v)
    * __A3_C1_REG__ (PipelineReg8 from PipelineReg.v)
    * __A2_C1_REG__ (PipelineReg8 from PipelineReg.v)
    * __P1_C1_REG__ (PipelineReg40 from PipelineReg.v)
    * __P0_C1_REG__ (PipelineReg40 from PipelineReg.v)
    * __B_C1_REG__ (PipelineReg32 from PipelineReg.v)
    * __A3_C2_REG__ (PipelineReg8 from PipelineReg.v)
    * __P2_C2_REG__ (PipelineReg40 from PipelineReg.v)
    * __P1_C2_REG__ (PipelineReg40 from PipelineReg.v)
    * __P0_C2_REG__ (PipelineReg40 from PipelineReg.v)
    * __B_C2_REG__ (PipelineReg32 from PipelineReg.v)
    * __P3_C3_REG__ (PipelineReg40 from PipelineReg.v)
    * __P2_C3_REG__ (PipelineReg40 from PipelineReg.v)
    * __P1_C3_REG__ (PipelineReg40 from PipelineReg.v)
    * __P0_C3_REG__ (PipelineReg40 from PipelineReg.v)
    * __B_C3_REG__ (PipelineReg32 from PipelineReg.v)
  * __PipeIntMul.ucf__
